# Generated by Django 2.1.4 on 2018-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recheio',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pastel',
            name='nome',
            field=models.CharField(default='Pastelao', max_length=45),
        ),
        migrations.RemoveField(
            model_name='pastel',
            name='recheio',
        ),
        migrations.AddField(
            model_name='pastel',
            name='recheio',
            field=models.CharField(default='Carne', max_length=45),
        ),
    ]
